### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by chenwinkk** [minshu-kim/Neural-Image-Stitching#11]
Dear author，
Have you encountered this kind of error when you use pysrwarp, and what is the approximate reason for it：

Traceback (most recent call last):
File "test.py", line 22, in
y, mask_y = warp.warp_by_function(x, m, f_inverse=False, sizes=sizes, fill=-255)
File "/opt/conda/envs/nis/lib/python3.6/site-packages/torch/autocast_mode.py", line 198, in decorate_autocast
return func(*args, **kwargs)
File "/opt/conda/envs/nis/lib/python3.6/site-packages/pysrwarp-1.0.0-py3.6-linux-x86_64.egg/srwarp/warp.py", line 206, in warp_by_function
grid_raw = grid.projective_grid(f, sizes)
File "/opt/conda/envs/nis/lib/python3.6/site-packages/torch/autocast_mode.py", line 198, in decorate_autocast
return func(*args, **kwargs)
File "/opt/conda/envs/nis/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
return func(*args, **kwargs)
File "/opt/conda/envs/nis/lib/python3.6/site-packages/pysrwarp-1.0.0-py3.6-linux-x86_64.egg/srwarp/grid.py", line 33, in projective_grid
grid = grid.t().contiguous()
RuntimeError: CUDA error: no kernel image is available for execution on the device

**Comment by minshu-kim** [comment]
Hello chenwinkk,

I haven't encountered this but the error log may indicate the built pysrwarp libraries are incompatible with your GPU devices. See [this](https://github.com/sanghyun-son/pysrwarp) repository's guidelines.

**Comment by kaikoko** [comment]
You need to make sure that the CUDA and PyTorch versions of your virtual environment are consistent with the default compilation environment in the pysrwarp code readme file, if they are not, you need to modify “pysrwarp/cuda/Makefile” file and then recompile pysrwarp.
