### ISSUE TITLE
Can you provide detailed information about the execution environment?

### ISSUE THREAD

**Issue by rein1685** [minshu-kim/Neural-Image-Stitching#4]
I am currently running on CentOS 7.9 and have installed torch 1.10.2 and torchgeometry 0.1.2 from the environment.yaml on GitHub to run eval_blending.py. However, I encountered the following error:

Traceback (most recent call last):
File "eval_blending.py", line 279, in <module>
main(config, save_path, args)
File "eval_blending.py", line 262, in main
valid_psnr = valid(loader, model, H_model)
File "eval_blending.py", line 225, in valid
stit_grid, stit_mask, sizes = prepare_ingredient(H_model, inp_tgt, inp_ref, tgt, ref)
File "eval_blending.py", line 103, in prepare_ingredient
four_pred, _ = model(inp_tgt, inp_ref, iters_lev0=6, iters_lev1=3, test_mode=True)
File "/home/hylee/anaconda3/envs/nis/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
return forward_call(*input, **kwargs)
File "/home/hylee/DLProject/stitching/models/ihn/network.py", line 110, in forward
coords1 = self.get_flow_now_4(four_point_disp)
File "/home/hylee/DLProject/stitching/models/ihn/network.py", line 36, in get_flow_now_4
H = tgm.get_perspective_transform(four_point_org, four_point_new)
File "/home/hylee/anaconda3/envs/nis/lib/python3.6/site-packages/torchgeometry/core/imgwarp.py", line 258, in get_perspective_transform
X, LU = torch.gesv(b, A)
AttributeError: module 'torch' has no attribute 'gesv'

It seems like the current version of the torchgeometry library does not support 'gesv'. Can you provide detailed information about the execution environment?

**Comment by minshu-kim** [comment]
Thanks for your sharing.

You can revise the line 258 in torchgeometry imgwarp.py to
```
X = torch.linalg.solve(A, b)
```
The code computes a unique solution of linear equations.
